'use client'

import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Download, Filter, Plus, Search, Shield, Table2, Users, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import Link from 'next/link'

type AdminData = { checks: Array<{ id:string; input_type:string; content:string|null; verdict:string; risk_score:number; confidence:number; category:string|null; model_source:string|null; created_at:string }>; users: Array<{ id:string; role:string; created_at:string }>; rules: Array<{ id:string; name:string; rule_type:string; pattern:string; enabled:boolean }>; metrics:{totalChecks:number;highRisk:number;activeUsers:number;averageConfidence:number;verdicts:Record<string,number>} }

export function AdminConsole() {
  const [data, setData] = useState<AdminData | null>(null); const [section, setSection] = useState('overview'); const [query, setQuery] = useState(''); const [risk, setRisk] = useState('all'); const [error, setError] = useState('')
  useEffect(() => { fetch('/api/admin/overview').then(async (response) => { if (!response.ok) throw new Error('Unable to load admin data'); return response.json() }).then(setData).catch((e) => { setError(e.message); setData({ checks: [], users: [], rules: [], metrics: { totalChecks: 0, highRisk: 0, activeUsers: 0, averageConfidence: 0, verdicts: {} } }) }) }, [])
  const filteredChecks = useMemo(() => (data?.checks ?? []).filter((item) => (risk === 'all' || (risk === 'high' ? item.risk_score >= 70 : item.risk_score < 70)) && `${item.content ?? ''} ${item.verdict}`.toLowerCase().includes(query.toLowerCase())), [data, query, risk])
  const exportCsv = () => { if (!data) return; const rows = [['id','type','content','verdict','risk_score','confidence','category','model_source','created_at'], ...filteredChecks.map((item) => [item.id,item.input_type,JSON.stringify(item.content ?? ''),item.verdict,String(item.risk_score),String(item.confidence),item.category ?? '',item.model_source ?? '',item.created_at])]; const blob = new Blob([rows.map((row) => row.join(',')).join('\n')], { type:'text/csv' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'scam-checks.csv'; anchor.click(); URL.revokeObjectURL(url) }
  const nav = [['overview','Overview',BarChart3],['users','Users',Users],['checks','All checks',Table2],['rules','Risk rules',Shield]] as const
  return <div className="dashboard-layout"><aside className="app-sidebar"><Link href="/" className="brand sidebar-brand"><span className="brand-mark"><Shield size={17}/></span><span>Scam Detector</span></Link><div className="sidebar-label">ADMIN CONSOLE</div><nav className="sidebar-nav">{nav.map(([id,label,Icon]) => <button key={id} className={section === id ? 'selected' : ''} onClick={() => setSection(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="sidebar-spacer"/><Link className="sidebar-link" href="/">Exit console</Link></aside><main className="dashboard-main"><div className="dashboard-topbar"><span className="mobile-brand">Admin console</span><span className="status-badge safe">LIVE BACKEND</span></div>{!data ? <div className="dashboard-view"><div className="empty-state">{error ? <><X size={28}/><h3>Backend unavailable</h3><p>{error}</p><button className="primary-button" onClick={()=>window.location.reload()}>Retry connection</button></> : <p>Loading secure admin data…</p>}</div></div> : section === 'overview' ? <Overview data={data}/> : section === 'users' ? <UsersView users={data.users} query={query} setQuery={setQuery}/> : section === 'checks' ? <ChecksView checks={filteredChecks} query={query} setQuery={setQuery} risk={risk} setRisk={setRisk} exportCsv={exportCsv}/> : <RulesView rules={data.rules}/>}</main></div>
}
function Overview({ data }: { data:AdminData }) { const chart = Object.entries(data.metrics.verdicts).map(([name,value]) => ({ name, value })); return <div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">ADMIN OVERVIEW</p><h1>System intelligence.</h1><p>Live metrics from your Supabase data.</p></div></div><div className="admin-metrics"><div><span>Total checks</span><strong>{data.metrics.totalChecks}</strong><small>Loaded from results</small></div><div><span>High risk</span><strong>{data.metrics.highRisk}</strong><small>Risk score 70+</small></div><div><span>Avg confidence</span><strong>{data.metrics.averageConfidence}%</strong><small>From stored checks</small></div><div><span>Total users</span><strong>{data.metrics.activeUsers}</strong><small>All profiles</small></div></div><div className="chart-card admin-chart"><div className="chart-card-title"><span>Verdict distribution</span><strong>{chart.length} verdict types</strong></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="name" stroke="var(--muted-foreground)"/><YAxis stroke="var(--muted-foreground)"/><Tooltip/><Bar dataKey="value" fill="var(--primary)" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div></div> }
function UsersView({ users, query, setQuery }:{users:AdminData['users'];query:string;setQuery:(v:string)=>void}) { const rows = users.filter((item) => `${item.id} ${item.role}`.toLowerCase().includes(query.toLowerCase())); return <div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">USER MANAGEMENT</p><h1>People and access.</h1><p>Review accounts and current role.</p></div><div className="search-field"><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search users"/></div></div><div className="data-table-wrap"><table><thead><tr><th>User ID</th><th>Role</th><th>Joined</th></tr></thead><tbody>{rows.map((user)=><tr key={user.id}><td><strong>{user.id}</strong></td><td>{user.role === 'admin' ? 'Admin' : 'Member'}</td><td>{new Date(user.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></div> }
function ChecksView({ checks, query, setQuery, risk, setRisk, exportCsv }:{checks:AdminData['checks'];query:string;setQuery:(v:string)=>void;risk:string;setRisk:(v:string)=>void;exportCsv:()=>void}) { return <div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">ALL CHECKS</p><h1>Scan activity.</h1><p>Filter the real checks stored in Supabase.</p></div><button className="primary-button" onClick={exportCsv}><Download size={15}/> Export CSV</button></div><div className="admin-toolbar"><div className="search-field"><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search checks"/></div><label><Filter size={14}/> Risk <select value={risk} onChange={(e)=>setRisk(e.target.value)}><option value="all">All</option><option value="high">High</option><option value="low">Below high</option></select></label></div><div className="data-table-wrap"><table><thead><tr><th>Content</th><th>Verdict</th><th>Category</th><th>Risk score</th><th>Confidence</th><th>Source</th><th>Created</th></tr></thead><tbody>{checks.map((item)=><tr key={item.id}><td><strong>{item.content ? item.content.slice(0,70) : '— (not logged)'}</strong><small>{item.input_type}</small></td><td>{item.verdict}</td><td>{item.category ?? '—'}</td><td>{item.risk_score}</td><td>{item.confidence}%</td><td>{item.model_source ?? '—'}</td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></div> }
function RulesView({ rules }:{rules:AdminData['rules']}) { return <div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">RULES AND SETTINGS</p><h1>Detector rules.</h1><p>Review the rules currently applied by your backend.</p></div><button className="primary-button" onClick={()=>alert('Rule creation is ready for your backend action.') }><Plus size={15}/> Add rule</button></div><div className="data-table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Pattern</th><th>Status</th></tr></thead><tbody>{rules.map((rule)=><tr key={rule.id}><td><strong>{rule.name}</strong></td><td>{rule.rule_type}</td><td>{rule.pattern}</td><td>{rule.enabled ? 'Enabled' : 'Disabled'}</td></tr>)}</tbody></table></div></div> }