'use client'

import { useMemo, useState } from 'react'
import { BarChart3, ClipboardCheck, LogOut, Search, Settings, Shield, Sparkles, Table2 } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { checkInput } from '@/lib/mock-api'

const history = [{ id:'CHK-1042', target:'paypaI-security.com', type:'URL', verdict:'Likely a scam', risk:'High', time:'2 min ago' },{ id:'CHK-1041', target:'Your parcel could not be delivered...', type:'Message', verdict:'Suspicious', risk:'Medium', time:'Yesterday' },{ id:'CHK-1040', target:'github.com/account/settings', type:'URL', verdict:'Looks safe', risk:'Low', time:'Yesterday' },{ id:'CHK-1039', target:'Invoice attached — review today', type:'Message', verdict:'Looks safe', risk:'Low', time:'Mar 18' }]
const activity = [{ day:'Mon', checks:14 },{day:'Tue',checks:22},{day:'Wed',checks:18},{day:'Thu',checks:31},{day:'Fri',checks:26},{day:'Sat',checks:12},{day:'Sun',checks:19}]
const split = [{name:'Safe',value:54,color:'#a9c7d8'},{name:'Suspicious',value:27,color:'#d3aa70'},{name:'High risk',value:19,color:'#c47c78'}]

function Sidebar({ section, setSection, onLogout }:{section:string;setSection:(value:string)=>void;onLogout:()=>void}) { return <aside className="app-sidebar"><Link href="/" className="brand sidebar-brand"><span className="brand-mark"><Shield size={17}/></span><span>Scam Detector</span></Link><div className="sidebar-label">WORKSPACE</div><nav className="sidebar-nav">{[['check','Check scam',ClipboardCheck],['history','History',Table2],['insights','Insights',BarChart3]].map(([id,label,Icon])=><button key={String(id)} className={section===id?'selected':''} onClick={()=>setSection(String(id))}><Icon size={17}/><span>{String(label)}</span></button>)}</nav><div className="sidebar-spacer"/><div className="sidebar-nav"><button className={section==='settings'?'selected':''} onClick={()=>setSection('settings')}><Settings size={17}/><span>Settings</span></button><button onClick={onLogout}><LogOut size={17}/><span>Log out</span></button></div><div className="profile-chip"><span className="avatar">JD</span><span><strong>Jordan Davis</strong><small>Free workspace</small></span></div></aside> }

function CheckView(){const [kind,setKind]=useState<'url'|'message'>('url');const [value,setValue]=useState('');const [loading,setLoading]=useState(false);const [result,setResult]=useState<any>(null);async function check(){if(!value.trim())return;setLoading(true);setResult(null);const response=await checkInput(value,kind);setResult(response);setLoading(false)}return <div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">QUICK CHECK</p><h1>Check before you click.</h1><p>Paste a URL or message and get a clear signal with the reasoning behind it.</p></div><span className="live-pill"><Sparkles size={13}/> Engine online</span></div><div className="dashboard-check-card"><div className="input-toggle"><button className={kind==='url'?'selected':''} onClick={()=>setKind('url')}>URL</button><button className={kind==='message'?'selected':''} onClick={()=>setKind('message')}>Message</button></div>{kind==='url'?<input value={value} onChange={e=>setValue(e.target.value)} placeholder="https://example.com/offer" onKeyDown={e=>e.key==='Enter'&&!e.nativeEvent.isComposing&&check()}/>:<textarea value={value} onChange={e=>setValue(e.target.value)} placeholder="Paste a suspicious message..." rows={6}/>}<button className="primary-button" disabled={loading||!value.trim()} onClick={check}>{loading?'Analyzing…':'Analyze now'} <ClipboardCheck size={16}/></button>{result&&<div className={`dashboard-result ${result.verdict==='Looks safe'?'safe':'risk'}`}><div><strong>{result.verdict}</strong><p>{result.summary}</p></div><span>{result.confidence}% confidence</span></div>}</div></div>}
function HistoryView(){const [query,setQuery]=useState('');const filtered=useMemo(()=>history.filter(item=>item.target.toLowerCase().includes(query.toLowerCase())||item.verdict.toLowerCase().includes(query.toLowerCase())),[query]);return <div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">CHECK HISTORY</p><h1>Your scan history.</h1><p>Review the signals you have checked in this workspace.</p></div><div className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search checks"/></div></div><div className="data-table-wrap"><table><thead><tr><th>Target</th><th>Type</th><th>Verdict</th><th>Risk</th><th>Checked</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.target}</strong><small>{item.id}</small></td><td>{item.type}</td><td>{item.verdict}</td><td><span className={`risk-dot ${item.risk.toLowerCase()}`}>{item.risk}</span></td><td>{item.time}</td></tr>)}</tbody></table></div></div>}
function InsightsView(){return <div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">YOUR INSIGHTS</p><h1>Patterns worth knowing.</h1><p>A simple view of how your checks are trending.</p></div></div><div className="chart-grid"><div className="chart-card"><div className="chart-card-title"><span>Checks this week</span><strong>142</strong></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="day" stroke="var(--muted-foreground)"/><YAxis stroke="var(--muted-foreground)"/><Tooltip/><Area type="monotone" dataKey="checks" stroke="var(--primary)" fill="color-mix(in srgb,var(--primary) 18%,transparent)"/></AreaChart></ResponsiveContainer></div></div><div className="chart-card"><div className="chart-card-title"><span>Verdict mix</span><strong>Last 30 days</strong></div><div className="chart-box donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={split} dataKey="value" innerRadius={55} outerRadius={82} paddingAngle={4}>{split.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{split.map(item=><span key={item.name}><i style={{background:item.color}}/>{item.name} {item.value}%</span>)}</div></div></div></div></div>}
export function UserDashboard(){const [section,setSection]=useState('check');const router=useRouter();return <div className="dashboard-layout"><Sidebar section={section} setSection={setSection} onLogout={()=>router.push('/login')}/><main className="dashboard-main"><div className="dashboard-topbar"><span className="mobile-brand">Scam Detector</span><Link href="/" className="back-link">Back to site</Link></div>{section==='check'?<CheckView/>:section==='history'?<HistoryView/>:section==='insights'?<InsightsView/>:<div className="dashboard-view"><div className="empty-state"><Settings size={28}/><h3>Workspace settings</h3><p>Settings and account controls will appear here.</p></div></div>}</main></div>}

export function AdminDashboard(){return <div className="dashboard-layout"><aside className="app-sidebar"><Link href="/" className="brand sidebar-brand"><span className="brand-mark"><Shield size={17}/></span><span>Scam Detector</span></Link><div className="sidebar-label">ADMIN CONSOLE</div><nav className="sidebar-nav"><button className="selected"><BarChart3 size={17}/><span>Overview</span></button><button><Table2 size={17}/><span>All checks</span></button><button><Shield size={17}/><span>Risk rules</span></button></nav><div className="sidebar-spacer"/><Link className="sidebar-link" href="/">Exit console</Link></aside><main className="dashboard-main"><div className="dashboard-topbar"><span className="mobile-brand">Admin console</span><span className="status-badge safe">SYSTEM NOMINAL</span></div><div className="dashboard-view"><div className="view-heading"><div><p className="eyebrow">ADMIN OVERVIEW</p><h1>System intelligence.</h1><p>Monitor every scan across the Scam Detector network.</p></div></div><div className="admin-metrics"><div><span>Total checks</span><strong>18,492</strong><small>+12.4% this week</small></div><div><span>High-risk rate</span><strong>31.8%</strong><small>-3.2% this week</small></div><div><span>Avg. confidence</span><strong>94.2%</strong><small>Across all models</small></div><div><span>Active users</span><strong>2,847</strong><small>+8.6% this month</small></div></div><div className="chart-card admin-chart"><div className="chart-card-title"><span>Checks by day</span><strong>Last 7 days</strong></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="day" stroke="var(--muted-foreground)"/><YAxis stroke="var(--muted-foreground)"/><Tooltip/><Bar dataKey="checks" fill="var(--primary)" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div></div></main></div>}
