export type Verdict = 'safe' | 'suspicious' | 'scam'
export type CheckResult = { verdict: Verdict; risk_score: number; confidence: number; summary: string; reasons: string[]; input_type: 'link' | 'message' | 'screenshot'; created_at: string }
export type MockUser = { email: string; role: 'user' | 'admin' }
const delay = (ms:number) => new Promise(resolve => setTimeout(resolve, ms))
const suspiciousWords = ['winner','prize','urgent','verify','gift card','wire transfer','crypto','claim now','password']
export async function checkInput(input:string, inputType:'link'|'message'|'screenshot'='link'):Promise<CheckResult>{
  await delay(850 + Math.random()*550)
  const text=input.toLowerCase(); const hits=suspiciousWords.filter(word=>text.includes(word)); const shortened=/bit\.ly|tinyurl|t\.co|goo\.gl/.test(text); const risky=hits.length+(shortened?2:0)+(inputType==='screenshot'?1:0)
  const verdict:Verdict=risky>=3?'scam':risky>0?'suspicious':'safe'; const risk_score=verdict==='scam'?82+Math.min(hits.length*3,14):verdict==='suspicious'?42+hits.length*7:8+Math.floor(Math.random()*12)
  return { verdict, risk_score, confidence:Math.min(98,78+risky*5+Math.floor(Math.random()*8)), summary:verdict==='safe'?'No major warning signs found in this sample.':'This sample contains signals commonly associated with deceptive or high-pressure scams.', reasons:verdict==='safe'?['No urgent payment language detected.','The content uses a familiar, consistent domain pattern.']: [...hits.slice(0,3).map(word=>`Uses high-pressure language around “${word}”.`), ...(shortened?['Shortened link hides the destination domain.']:[]), ...(inputType==='screenshot'?['Visual layout resembles a common impersonation flow.']:[])], input_type:inputType, created_at:new Date().toISOString() }
}
export async function signIn(email:string,password:string):Promise<{user?:MockUser;error?:string}>{ await delay(650); if(password.toLowerCase().includes('wrong')) return {error:'Invalid email or password.'}; return {user:{email,role:email.toLowerCase().includes('admin')?'admin':'user'}} }
export async function signUp(email:string,password:string):Promise<{user?:MockUser;error?:string}>{ await delay(800); if(password.toLowerCase().includes('wrong')) return {error:'Unable to create account right now.'}; return {user:{email,role:'user'}} }
export function getHistory(){return [{input:'prime-deal-alert.com/claim',verdict:'scam',type:'Link',time:'3 hours ago'},{input:'support-paypal-help.net',verdict:'suspicious',type:'Link',time:'Yesterday'},{input:'Your bank verification message',verdict:'suspicious',type:'Message',time:'2 days ago'},{input:'wikipedia.org/article',verdict:'safe',type:'Link',time:'4 days ago'},{input:'Neighborhood market receipt',verdict:'safe',type:'Message',time:'5 days ago'},{input:'gift-card-winner.co',verdict:'scam',type:'Link',time:'6 days ago'},{input:'Delivery update screenshot',verdict:'suspicious',type:'Screenshot',time:'1 week ago'},{input:'google.com',verdict:'safe',type:'Link',time:'1 week ago'}]}
